name: Docker CakePHP CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test CakePHP Install

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Start Docker container
      run: |
        docker-compose up -d

    - name: Run tests
      run: |
        docker cp test/run_tests.sh test_app:/var/www/
        docker exec test_app /var/www/run_tests.sh

    - name: Stop Docker container
      run: |
        docker-compose down
