name: Docker Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define tag name (ex) 4.2.1-php8 -> 4-php8
        id: define_tag
        run: |
          tag_name=$(echo ${GITHUB_REF##*/} | sed -r "s/([0-9]+).([0-9]+).([0-9]+)-php([0-9]+)/\1-php\4/")
          echo "::set-output name=tag::${tag_name}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          push: true
          tags: sukun1899/cakephp:latest,sukun1899/cakephp:${{ steps.define_tag.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
