name: Docker Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-18.04
    name: Release Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define tag name
        id: define_tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF##*/}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: sukun1899/cakephp:${{ steps.define_tag.outputs.tag }}
